export type FlashMarketStatus = "active" | "locked" | "resolving" | "finalized" | "cancelled";

export type FlashMarketKind = "sport" | "crypto" | "irl";
export type FlashCryptoVisualMode = "price" | "graduation";
export type FlashCryptoSourceType = "pump_fun" | "major";

export type FlashMarket = {
  liveMicroId: string;
  providerMatchId: string;
  marketAddress: string;
  marketId: string | null;
  question: string;
  league: string | null;
  sport: string | null;
  providerImageUrl: string | null;
  marketImageUrl: string | null;
  heroImageUrl: string | null;
  homeTeam: string;
  awayTeam: string;
  homeLogo: string | null;
  awayLogo: string | null;
  startScoreHome: number;
  startScoreAway: number;
  currentScoreHome: number;
  currentScoreAway: number;
  minute: number | null;
  windowStart?: string | null;
  windowEnd: string | null;
  startTime?: string | null;
  endTime?: string | null;
  loopSequence: number | null;
  loopPhase: string | null;
  remainingSec: number | null;
  status: FlashMarketStatus;
  volume: number;
  createdAt: string;

  // Crypto flash market fields
  kind: FlashMarketKind;
  tokenMint?: string | null;
  tokenSymbol?: string | null;
  tokenName?: string | null;
  tokenImageUri?: string | null;
  cryptoSourceType?: FlashCryptoSourceType | null;
  majorSymbol?: string | null;
  majorPair?: string | null;
  providerName?: string | null;
  providerSource?: string | null;
  cryptoType?: "flash_crypto_price" | "flash_crypto_graduation" | null;
  cryptoMode?: FlashCryptoVisualMode | null;
  priceStart?: number | null;
  priceEnd?: number | null;
  progressStart?: number | null;
  progressCurrent?: number | null;
  progressEnd?: number | null;
  didGraduateStart?: boolean | null;
  didGraduateEnd?: boolean | null;
  remainingToGraduate?: number | null;
  durationMinutes?: number | null;
};
